site_name: PepsWiki
site_url: https://julienpeps.github.io/Wiki
copyright: Copyright &copy; 2024 Julien Pepinster
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/julienpeps/
    - icon: fontawesome/brands/github
      link: https://github.com/julienpeps
theme:
  name: material
  palette:
    scheme: slate
    language: en
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.indexes
    - search.suggest
    - content.code.copy
    - content.tabs.link
plugins:
  - search
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
